server:
    port: 10001
#    servlet:
#        #jetty
#        contextPath: "/api/monitoreo/*" 
#        #tomcat
#        context-path: "/api/monitoreo"
#
spring:
  datasource:
    password: sol123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres